AUDIO_REGS = ['0800', '0804', '0808', '080c', '0810', '0814', '0818', '081c', '0820', '0824', '0828', '082c', '0830', '0834', '0838', '083c', '0840', '0844', ]

AUDIO_REG_NAMES = [ 'CPCAP_REG_VAUDIOC', 'CPCAP_REG_CC', 'CPCAP_REG_CDI', 'CPCAP_REG_SDAC', 'CPCAP_REG_SDACDI', 'CPCAP_REG_TXI', 'CPCAP_REG_TXMP', 'CPCAP_REG_RXOA', 'CPCAP_REG_RXVC', 'CPCAP_REG_RXCOA', 'CPCAP_REG_RXSDOA', 'CPCAP_REG_RXEPOA', 'CPCAP_REG_RXLL', 'CPCAP_REG_A2LA', 'CPCAP_REG_MIPIS1', 'CPCAP_REG_MIPIS2', 'CPCAP_REG_MIPIS3', 'CPCAP_REG_LVAB', ]

AUDIO_REG_BITS = {
    'CPCAP_REG_VAUDIOC': {
        'CPCAP_BIT_AUDIO_LOW_PWR':           6,
        'CPCAP_BIT_AUD_LOWPWR_SPEED':        5,
        'CPCAP_BIT_VAUDIOPRISTBY':           4,
        'CPCAP_BIT_VAUDIO_MODE1':            2,
        'CPCAP_BIT_VAUDIO_MODE0':            1,
        'CPCAP_BIT_V_AUDIO_EN':              0,
    },
    'CPCAP_REG_CC': {
        'CPCAP_BIT_CDC_CLK2':                15,
        'CPCAP_BIT_CDC_CLK1':                14,
        'CPCAP_BIT_CDC_CLK0':                13,
        'CPCAP_BIT_CDC_SR3':                 12,
        'CPCAP_BIT_CDC_SR2':                 11,
        'CPCAP_BIT_CDC_SR1':                 10,
        'CPCAP_BIT_CDC_SR0':                 9,
        'CPCAP_BIT_CDC_CLOCK_TREE_RESET':    8,
        'CPCAP_BIT_MIC2_CDC_EN':             7,
        'CPCAP_BIT_CDC_EN_RX':               6,
        'CPCAP_BIT_DF_RESET':                5,
        'CPCAP_BIT_MIC1_CDC_EN':             4,
        'CPCAP_BIT_AUDOHPF_1':       3,
        'CPCAP_BIT_AUDOHPF_0':       2,
        'CPCAP_BIT_AUDIHPF_1':       1,
        'CPCAP_BIT_AUDIHPF_0':       0,
    },
    'CPCAP_REG_CDI': {
        'CPCAP_BIT_CDC_PLL_SEL':             15,
        'CPCAP_BIT_CLK_IN_SEL':              13,
        'CPCAP_BIT_DIG_AUD_IN':              12,
        'CPCAP_BIT_CDC_CLK_EN':              11,
        'CPCAP_BIT_CDC_DIG_AUD_FS1':         10,
        'CPCAP_BIT_CDC_DIG_AUD_FS0':         9,
        'CPCAP_BIT_MIC2_TIMESLOT2':          8,
        'CPCAP_BIT_MIC2_TIMESLOT1':          7,
        'CPCAP_BIT_MIC2_TIMESLOT0':          6,
        'CPCAP_BIT_MIC1_RX_TIMESLOT2':       5,
        'CPCAP_BIT_MIC1_RX_TIMESLOT1':       4,
        'CPCAP_BIT_MIC1_RX_TIMESLOT0':       3,
        'CPCAP_BIT_FS_INV':                  2,
        'CPCAP_BIT_CLK_INV':                 1,
        'CPCAP_BIT_SMB_CDC':                 0,
    },

    'CPCAP_REG_SDAC': {
        'CPCAP_BIT_FSYNC_CLK_IN_COMMON':     11,
        'CPCAP_BIT_SLAVE_PLL_CLK_INPUT':     10,
        'CPCAP_BIT_ST_CLOCK_TREE_RESET':     9,
        'CPCAP_BIT_DF_RESET_ST_DAC':         8,
        'CPCAP_BIT_ST_SR3':                  7,
        'CPCAP_BIT_ST_SR2':                  6,
        'CPCAP_BIT_ST_SR1':                  5,
        'CPCAP_BIT_ST_SR0':                  4,
        'CPCAP_BIT_ST_DAC_CLK2':             3,
        'CPCAP_BIT_ST_DAC_CLK1':             2,
        'CPCAP_BIT_ST_DAC_CLK0':             1,
        'CPCAP_BIT_ST_DAC_EN':               0,
    },


    'CPCAP_REG_SDACDI': {
        'CPCAP_BIT_ST_L_TIMESLOT2':          13,
        'CPCAP_BIT_ST_L_TIMESLOT1':          12,
        'CPCAP_BIT_ST_L_TIMESLOT0':          11,
        'CPCAP_BIT_ST_R_TIMESLOT2':          10,
        'CPCAP_BIT_ST_R_TIMESLOT1':          9,
        'CPCAP_BIT_ST_R_TIMESLOT0':          8,
        'CPCAP_BIT_ST_DAC_CLK_IN_SEL':       7,
        'CPCAP_BIT_ST_FS_INV':               6,
        'CPCAP_BIT_ST_CLK_INV':              5,
        'CPCAP_BIT_ST_DIG_AUD_FS1':          4,
        'CPCAP_BIT_ST_DIG_AUD_FS0':          3,
        'CPCAP_BIT_DIG_AUD_IN_ST_DAC':       2,
        'CPCAP_BIT_ST_CLK_EN':               1,
        'CPCAP_BIT_SMB_ST_DAC':              0,
    },


    'CPCAP_REG_TXI': {
        'CPCAP_BIT_PTT_TH':        15,
        'CPCAP_BIT_PTT_CMP_EN':        14,
        'CPCAP_BIT_HS_ID_TX':      13,
        'CPCAP_BIT_MB_ON2':        12,
        'CPCAP_BIT_MB_ON1L':       11,
        'CPCAP_BIT_MB_ON1R':       10,
        'CPCAP_BIT_RX_L_ENCODE':       9,
        'CPCAP_BIT_RX_R_ENCODE':       8,
        'CPCAP_BIT_MIC2_MUX':      7,
        'CPCAP_BIT_MIC2_PGA_EN':       6,
        'CPCAP_BIT_CDET_DIS':      5,
        'CPCAP_BIT_EMU_MIC_MUX':       4,
        'CPCAP_BIT_HS_MIC_MUX':        3,
        'CPCAP_BIT_MIC1_MUX':      2,
        'CPCAP_BIT_MIC1_PGA_EN':       1,
        'CPCAP_BIT_DLM':           0,
    },


    'CPCAP_REG_TXMP': {
        'CPCAP_BIT_MB_BIAS_R1':              11,
        'CPCAP_BIT_MB_BIAS_R0':              10,
        'CPCAP_BIT_MIC2_GAIN_4':             9,
        'CPCAP_BIT_MIC2_GAIN_3':             8,
        'CPCAP_BIT_MIC2_GAIN_2':             7,
        'CPCAP_BIT_MIC2_GAIN_1':             6,
        'CPCAP_BIT_MIC2_GAIN_0':             5,
        'CPCAP_BIT_MIC1_GAIN_4':             4,
        'CPCAP_BIT_MIC1_GAIN_3':             3,
        'CPCAP_BIT_MIC1_GAIN_2':             2,
        'CPCAP_BIT_MIC1_GAIN_1':             1,
        'CPCAP_BIT_MIC1_GAIN_0':             0,
    },



    'CPCAP_REG_RXOA': {
        'CPCAP_BIT_UNUSED_519_15':     15,
        'CPCAP_BIT_UNUSED_519_14':     14,
        'CPCAP_BIT_UNUSED_519_13':     13,
        'CPCAP_BIT_STDAC_LOW_PWR_DISABLE': 12,
        'CPCAP_BIT_HS_LOW_PWR':        11,
        'CPCAP_BIT_HS_ID_RX':      10,
        'CPCAP_BIT_ST_HS_CP_EN':       9,
        'CPCAP_BIT_EMU_SPKR_R_EN':     8,
        'CPCAP_BIT_EMU_SPKR_L_EN':     7,
        'CPCAP_BIT_HS_L_EN':       6,
        'CPCAP_BIT_HS_R_EN':       5,
        'CPCAP_BIT_A4_LINEOUT_L_EN':   4,
        'CPCAP_BIT_A4_LINEOUT_R_EN':   3,
        'CPCAP_BIT_A2_LDSP_L_EN':      2,
        'CPCAP_BIT_A2_LDSP_R_EN':      1,
        'CPCAP_BIT_A1_EAR_EN':     0,
    },


    'CPCAP_REG_RXVC': {
        'CPCAP_BIT_VOL_EXT3':                15,
        'CPCAP_BIT_VOL_EXT2':                14,
        'CPCAP_BIT_VOL_EXT1':                13,
        'CPCAP_BIT_VOL_EXT0':                12,
        'CPCAP_BIT_VOL_DAC3':                11,
        'CPCAP_BIT_VOL_DAC2':                10,
        'CPCAP_BIT_VOL_DAC1':                9,
        'CPCAP_BIT_VOL_DAC0':                8,
        'CPCAP_BIT_VOL_DAC_LSB_1dB1':        7,
        'CPCAP_BIT_VOL_DAC_LSB_1dB0':        6,
        'CPCAP_BIT_VOL_CDC3':                5,
        'CPCAP_BIT_VOL_CDC2':                4,
        'CPCAP_BIT_VOL_CDC1':                3,
        'CPCAP_BIT_VOL_CDC0':                2,
        'CPCAP_BIT_VOL_CDC_LSB_1dB1':        1,
        'CPCAP_BIT_VOL_CDC_LSB_1dB0':        0,
    },


    'CPCAP_REG_RXCOA': {
        'CPCAP_BIT_PGA_CDC_EN':              10,
        'CPCAP_BIT_CDC_SW':                  9,
        'CPCAP_BIT_PGA_OUTR_USBDP_CDC_SW':   8,
        'CPCAP_BIT_PGA_OUTL_USBDN_CDC_SW':   7,
        'CPCAP_BIT_ALEFT_HS_CDC_SW':         6,
        'CPCAP_BIT_ARIGHT_HS_CDC_SW':        5,
        'CPCAP_BIT_A4_LINEOUT_L_CDC_SW':     4,
        'CPCAP_BIT_A4_LINEOUT_R_CDC_SW':     3,
        'CPCAP_BIT_A2_LDSP_L_CDC_SW':        2,
        'CPCAP_BIT_A2_LDSP_R_CDC_SW':        1,
        'CPCAP_BIT_A1_EAR_CDC_SW':           0,
    },



    'CPCAP_REG_RXSDOA': {
        'CPCAP_BIT_PGA_DAC_EN':              12,
        'CPCAP_BIT_ST_DAC_SW':               11,
        'CPCAP_BIT_MONO_DAC1':               10,
        'CPCAP_BIT_MONO_DAC0':               9,
        'CPCAP_BIT_PGA_OUTR_USBDP_DAC_SW':   8,
        'CPCAP_BIT_PGA_OUTL_USBDN_DAC_SW':   7,
        'CPCAP_BIT_ALEFT_HS_DAC_SW':         6,
        'CPCAP_BIT_ARIGHT_HS_DAC_SW':        5,
        'CPCAP_BIT_A4_LINEOUT_L_DAC_SW':     4,
        'CPCAP_BIT_A4_LINEOUT_R_DAC_SW':     3,
        'CPCAP_BIT_A2_LDSP_L_DAC_SW':        2,
        'CPCAP_BIT_A2_LDSP_R_DAC_SW':        1,
        'CPCAP_BIT_A1_EAR_DAC_SW':           0,
    },


    'CPCAP_REG_RXEPOA': {
        'CPCAP_BIT_PGA_EXT_L_EN':            14,
        'CPCAP_BIT_PGA_EXT_R_EN':            13,
        'CPCAP_BIT_PGA_IN_L_SW':             12,
        'CPCAP_BIT_PGA_IN_R_SW':             11,
        'CPCAP_BIT_MONO_EXT1':               10,
        'CPCAP_BIT_MONO_EXT0':               9,
        'CPCAP_BIT_PGA_OUTR_USBDP_EXT_SW':   8,
        'CPCAP_BIT_PGA_OUTL_USBDN_EXT_SW':   7,
        'CPCAP_BIT_ALEFT_HS_EXT_SW':         6,
        'CPCAP_BIT_ARIGHT_HS_EXT_SW':        5,
        'CPCAP_BIT_A4_LINEOUT_L_EXT_SW':     4,
        'CPCAP_BIT_A4_LINEOUT_R_EXT_SW':     3,
        'CPCAP_BIT_A2_LDSP_L_EXT_SW':        2,
        'CPCAP_BIT_A2_LDSP_R_EXT_SW':        1,
        'CPCAP_BIT_A1_EAR_EXT_SW':           0,
    },


    'CPCAP_REG_A2LA': {
        'CPCAP_BIT_NCP_CLK_SYNC':            7,
        'CPCAP_BIT_A2_CLK_SYNC':             6,
        'CPCAP_BIT_A2_FREE_RUN':             5,
        'CPCAP_BIT_A2_CLK2':                 4,
        'CPCAP_BIT_A2_CLK1':                 3,
        'CPCAP_BIT_A2_CLK0':                 2,
        'CPCAP_BIT_A2_CLK_IN':               1,
        'CPCAP_BIT_A2_CONFIG':               0,
    },

}
